In [1]:
import numpy as np

In [2]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [3]:
ar = np.ones(11)
ar

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.empty(8)

array([4.68151916e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
 0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000])

In [10]:
u = np.arange(1,77,3)
u

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55, 58, 61, 64, 67, 70, 73, 76])

In [7]:
h = [5,89,76,34,5]
print(type(h))
print(type(u))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
k = np.linspace(0,10,num=5)
k

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [12]:
mlista = np.array([45,23,4,8,9,12,3])
print(mlista)
print(type(mlista))

[45 23  4  8  9 12  3]
<class 'numpy.ndarray'>


In [13]:
dlista = np.array(h)
print(dlista)
print(type(dlista))

[ 5 89 76 34  5]
<class 'numpy.ndarray'>


In [23]:
krt = (6,3,8,9,3,62,57,7)
npk = np.array(krt,dtype=float)
npk

array([ 6., 3., 8., 9., 3., 62., 57., 7.])

In [24]:
ik = ("Jan","Olaf","Olga","Lena",5344,56,0.56,True)
ikm = np.array(ik)
print(ikm)
print(type(ikm))

['Jan' 'Olaf' 'Olga' 'Lena' '5344' '56' '0.56' 'True']
<class 'numpy.ndarray'>


In [30]:
el = ikm[6]
print(el)
print(type(el))
print(eval(el)*4)
print(float(el)*4)
print(np.float32(el)*4)

0.56
<class 'numpy.str_'>
2.24
2.24
2.240000009536743


In [39]:
zb = {4,5,2,67,12,1,8,9,4}
zbk = np.array(zb)
print(zbk)
print(type(zbk))

{1, 2, 67, 4, 5, 8, 9, 12}
<class 'numpy.ndarray'>


In [42]:
nb = [98,0,12,5,6,-7,-88,123,45,67,-34,13,578,987,-456,78,46,-7]
nnb = np.array(nb)
nnb

array([ 98, 0, 12, 5, 6, -7, -88, 123, 45, 67, -34,
 13, 578, 987, -456, 78, 46, -7])

In [49]:
new_nb = nnb.copy()

nnb.sort()
print(nnb)
print(new_nb)

[-456  -88  -34   -7   -7    0    5    6   12   13   45   46   67   78
   98  123  578  987]
[  98    0   12    5    6   -7  -88  123   45   67  -34   13  578  987
 -456   78   46   -7]


In [50]:
l1 = [8.8,1.3,4.7,2,23]
l2 = [True,False,0,1]
l3 = [34,2,78]

l1 = l1+l2+l3
print(l1)

[8.8, 1.3, 4.7, 2, 23, True, False, 0, 1, 34, 2, 78]


In [52]:
a = np.array([3,5,7,11,23])
b = np.array([23,6.6,7,8.8,9,10,56,7.1])
c = np.array([56,99])

big = np.concatenate((a,b,c))
big

array([ 3. , 5. , 7. , 11. , 23. , 23. , 6.6, 7. , 8.8, 9. , 10. ,
 56. , 7.1, 56. , 99. ])

In [53]:
bx = b*5
bx

array([115. , 33. , 35. , 44. , 45. , 50. , 280. , 35.5])

In [56]:
#tworzenie macierzy
x = np.array([[3,4],[19,6]])
print(x)
print("_"*50)
z = np.array([[7,11],[45,2]])
print(z)

[[ 3  4]
 [19  6]]
__________________________________________________
[[ 7 11]
 [45  2]]


In [60]:
print(x[0][1])
print(x[0,1])

4
4


In [57]:
zx = [[56,3],[98,76]]
print(zx)

[[56, 3], [98, 76]]


In [63]:
print(zx[0][1])
# print(zx[0,1])

3


In [66]:
p = np.concatenate((x,z),axis=1)
p

array([[ 3, 4, 7, 11],
 [19, 6, 45, 2]])

In [67]:
prosta = np.arange(12)
prosta

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [74]:
pp = prosta.reshape(3,4)
pp

array([[ 0, 1, 2, 3],
 [ 4, 5, 6, 7],
 [ 8, 9, 10, 11]])

In [75]:
we = pp.reshape(12)
we

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [77]:
aar = np.array([1,6,67,8,9,34,-3,-2,17,87,12,-3,13])
print(aar.shape)

(13,)


In [78]:
print(ar[:4])

[1. 1. 1. 1.]


In [79]:
print(ar[5:])

[1. 1. 1. 1. 1. 1.]


In [80]:
w = np.array([[1,2,3,4],[99,34,56,77],[29,4,16,76]])
w

array([[ 1, 2, 3, 4],
 [99, 34, 56, 77],
 [29, 4, 16, 76]])

In [81]:
print(w[w<5])

[1 2 3 4 4]


In [82]:
pc = (w>10)
print(w[pc])

[99 34 56 77 29 16 76]


In [83]:
pv = (w%2==0)
print(w[pv])

[ 2  4 34 56  4 16 76]


In [84]:
s = w[(w>2)&(w<21)]
print(s)

[ 3  4  4 16]


In [85]:
s = w[(w<8)|(w>50)]
print(s)

[ 1  2  3  4 99 56 77  4 76]


In [86]:
#operacje na macierzach
dane = np.array([1,3,8])
ones = np.ones(3,dtype=int)
tw = np.array([2,2,3])

In [87]:
#suma
print(dane+ones)

[2 4 9]


In [88]:
#różnica
print(dane-ones)

[0 2 7]


In [89]:
#mnożenie
print(dane*tw)

[ 2  6 24]


In [90]:
print(dane/tw)

[0.5        1.5        2.66666667]


In [91]:
tab = np.array([[1,6],[27,19]])
print(tab)

[[ 1  6]
 [27 19]]


In [92]:
print(tab.sum(axis=0))
print(tab.sum(axis=1))

[28 25]
[ 7 46]


In [93]:
print(tab*2.45)

[[ 2.45 14.7 ]
 [66.15 46.55]]


In [94]:
print(tab.max())
print(tab.min())
print(tab.mean())

27
1
13.25
