In [1]:
import numpy as np
import deap as dp

In [2]:
arr = np.array([[1.,2.,3.],[6.,8.,9.]])
arr

array([[1., 2., 3.],
 [6., 8., 9.]])

In [3]:
arr*arr

array([[ 1., 4., 9.],
 [36., 64., 81.]])

In [4]:
arr-arr

array([[0., 0., 0.],
 [0., 0., 0.]])

In [5]:
1/arr

array([[1. , 0.5 , 0.33333333],
 [0.16666667, 0.125 , 0.11111111]])

In [6]:
arr**0.5

array([[1. , 1.41421356, 1.73205081],
 [2.44948974, 2.82842712, 3. ]])

In [7]:
arr2 = np.array([[0.,4.,1.],[7.,5.,14.]])
arr2

array([[ 0., 4., 1.],
 [ 7., 5., 14.]])

In [8]:
arr2>arr

array([[False, True, False],
 [ True, False, True]])

In [9]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2D[2]

array([7, 8, 9])

In [10]:
arr2D[0][2]

3

In [11]:
arr2D[0,2]

3