In [1]:
import numpy as np

In [2]:
arr = np.random.randn(5,4)
arr

array([[-0.96519544, -1.14782704, -0.19779357, -0.94419107],
 [-0.1181881 , 1.62503276, 0.01310286, 1.14912201],
 [ 0.94588563, 1.00002033, 0.17287933, -1.72823946],
 [-0.33473589, 0.11593095, 0.36366638, 0.83008237],
 [-0.01854094, -0.01087696, -1.02638339, -0.47023528]])

In [3]:
arr.mean()

-0.03732422624546452

In [6]:
arr.mean(axis=1)

array([-0.81375178, 0.66726738, 0.09763646, 0.24373595, -0.38150915])

In [7]:
arr = np.array([0,2,4,5,6,7,9,11,22])
arr

array([ 0, 2, 4, 5, 6, 7, 9, 11, 22])

In [8]:
arr.cumsum()

array([ 0, 2, 6, 11, 17, 24, 33, 44, 66])

In [9]:
arr = np.array([[0,1,2],[6,7,8],[10,15,19]])
arr

array([[ 0, 1, 2],
 [ 6, 7, 8],
 [10, 15, 19]])

In [10]:
arr.cumsum(axis=0)

array([[ 0, 1, 2],
 [ 6, 8, 10],
 [16, 23, 29]])

In [11]:
arr.cumprod(axis=1)

array([[ 0, 0, 0],
 [ 6, 42, 336],
 [ 10, 150, 2850]])

In [21]:
arr = np.random.randn(100)
(arr>0).sum()

49

In [22]:
bools = np.array([False,False,True,False])
bools.any()

True

In [23]:
bools.all()

False

In [24]:
names = np.array(['Jan','Anna','Henryk','Jan','Jan','Anna','Olaf'])
np.unique(names)

array(['Anna', 'Henryk', 'Jan', 'Olaf'], dtype='%lt;U6')

In [25]:
sorted(set(names))

['Anna', 'Henryk', 'Jan', 'Olaf']

In [26]:
values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])

array([ True, False, False, True, True, False, True])

In [28]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])
y = np.array([[6.,23.],[-1,7],[8,9]])

In [29]:
y

array([[ 6., 23.],
 [-1., 7.],
 [ 8., 9.]])

In [31]:
x

array([[1., 2., 3.],
 [4., 5., 6.]])

In [30]:
np.dot(x,y)

array([[ 28., 64.],
 [ 67., 181.]])

In [32]:
np.dot(x,np.ones(3))

array([ 6., 15.])