In [54]:
import numpy as np
import deap as dp

In [55]:
arr = np.array([[1.,2.,3.],[6.,8.,9.]])
arr

array([[1., 2., 3.],
 [6., 8., 9.]])

In [56]:
arr*arr

array([[ 1., 4., 9.],
 [36., 64., 81.]])

In [57]:
arr-arr

array([[0., 0., 0.],
 [0., 0., 0.]])

In [58]:
1/arr

array([[1. , 0.5 , 0.33333333],
 [0.16666667, 0.125 , 0.11111111]])

In [59]:
arr**0.5

array([[1. , 1.41421356, 1.73205081],
 [2.44948974, 2.82842712, 3. ]])

In [60]:
arr2 = np.array([[0.,4.,1.],[7.,5.,14.]])
arr2

array([[ 0., 4., 1.],
 [ 7., 5., 14.]])

In [61]:
arr2>arr

array([[False, True, False],
 [ True, False, True]])

In [62]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2D[2]

array([7, 8, 9])

In [63]:
arr2D[0][2]

3

In [64]:
arr2D[0,2]

3

Budowa **tensora** (tablica 3D)

In [65]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d3 = np.array([[[1,2,3],[4,5,6],[23,24,25]],[[7,8,9],[10,11,12],[67,68,69]],[[31,32,33],[45,46,47],[89,90,91]]])

In [66]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [67]:
arr3d3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [23, 24, 25]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [67, 68, 69]],

       [[31, 32, 33],
        [45, 46, 47],
        [89, 90, 91]]])

In [68]:
print(arr3d.shape)
print(arr3d3.shape)

(2, 2, 3)
(3, 3, 3)


In [69]:
arr3d[0,1,1]

5

In [70]:
old_values = np.array(arr3d[0])
arr3d[0] = 42
arr3d[0,1,2] = 22
arr3d

array([[[42, 42, 42],
        [42, 42, 22]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [71]:
arr3d[0] == old_values

array([[False, False, False],
 [False, False, False]])

In [72]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [89]:
names = np.array(['Olga','Anna','Jacek','Piotr','Leon','Maria','Leon'])
data = np.random.randn(7,4)

In [90]:
names

array(['Olga', 'Anna', 'Jacek', 'Piotr', 'Leon', 'Maria', 'Leon'],
 dtype='%lt;U5')

In [91]:
data

array([[ 0.08650947, 0.95972659, -1.5713736 , 0.9515434 ],
 [-1.53854212, -0.51006029, -0.8734057 , -1.40039482],
 [-0.69190397, -0.84402182, 1.06491347, 0.34633834],
 [ 1.06530407, 2.15085108, -0.34113599, 1.42162115],
 [-0.04350099, 0.68098816, -1.80294691, 0.34629367],
 [-0.56074119, 0.48575469, -0.77479308, 0.04589436],
 [-0.77402433, -0.5423209 , 0.05282443, 0.4093474 ]])

In [92]:
data[names=="Leon"]

array([[-0.04350099, 0.68098816, -1.80294691, 0.34629367],
 [-0.77402433, -0.5423209 , 0.05282443, 0.4093474 ]])

In [93]:
data[names=="Leon",2:]

array([[-1.80294691, 0.34629367],
 [ 0.05282443, 0.4093474 ]])

In [94]:
data[names=="Leon",3]

array([0.34629367, 0.4093474 ])

In [95]:
names != "Leon"

array([ True, True, True, True, False, True, False])

In [96]:
data[~(names=='Leon')]

array([[ 0.08650947, 0.95972659, -1.5713736 , 0.9515434 ],
 [-1.53854212, -0.51006029, -0.8734057 , -1.40039482],
 [-0.69190397, -0.84402182, 1.06491347, 0.34633834],
 [ 1.06530407, 2.15085108, -0.34113599, 1.42162115],
 [-0.56074119, 0.48575469, -0.77479308, 0.04589436]])

In [97]:
maska = (names=="Leon") | (names=="Anna")
maska

array([False, True, False, False, True, False, True])

In [98]:
data[maska]

array([[-1.53854212, -0.51006029, -0.8734057 , -1.40039482],
 [-0.04350099, 0.68098816, -1.80294691, 0.34629367],
 [-0.77402433, -0.5423209 , 0.05282443, 0.4093474 ]])

In [99]:
data[data<0] =0
data

array([[0.08650947, 0.95972659, 0. , 0.9515434 ],
 [0. , 0. , 0. , 0. ],
 [0. , 0. , 1.06491347, 0.34633834],
 [1.06530407, 2.15085108, 0. , 1.42162115],
 [0. , 0.68098816, 0. , 0.34629367],
 [0. , 0.48575469, 0. , 0.04589436],
 [0. , 0. , 0.05282443, 0.4093474 ]])

In [100]:
data[names!="Leon"] = 8
data

array([[8. , 8. , 8. , 8. ],
 [8. , 8. , 8. , 8. ],
 [8. , 8. , 8. , 8. ],
 [8. , 8. , 8. , 8. ],
 [0. , 0.68098816, 0. , 0.34629367],
 [8. , 8. , 8. , 8. ],
 [0. , 0. , 0.05282443, 0.4093474 ]])

In [101]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
 [1., 1., 1., 1.],
 [2., 2., 2., 2.],
 [3., 3., 3., 3.],
 [4., 4., 4., 4.],
 [5., 5., 5., 5.],
 [6., 6., 6., 6.],
 [7., 7., 7., 7.]])

In [102]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
 [3., 3., 3., 3.],
 [0., 0., 0., 0.],
 [6., 6., 6., 6.]])

In [103]:
arr[[-3,-6,-8]]

array([[5., 5., 5., 5.],
 [2., 2., 2., 2.],
 [0., 0., 0., 0.]])

In [104]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14]])

In [105]:
arr.T

array([[ 0, 5, 10],
 [ 1, 6, 11],
 [ 2, 7, 12],
 [ 3, 8, 13],
 [ 4, 9, 14]])

In [106]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [108]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [110]:
arr2 = arr.transpose((1,0,2))
arr2

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])